### ISSUE TITLE
你好 推流生成的地址中 为什么有？ （问号）怎么能去掉

### ISSUE THREAD

**Issue by makeyu** [pili-engineering/PLCameraStreamingKit#101]

**Comment by longbai** [comment]
为什么要去掉？

**Comment by makeyu** [comment]
服务器 需要切 m3u8  生成的文件 因为问号 播不了。（因为是用现成的m3u8切片库，3u8片段地址也带问号。这样播放时，播不了。），您看有好的解决方法吗。

**Comment by longbai** [comment]
是用七牛的生成直播切片服务么？

**Comment by makeyu** [comment]
不是 好像 那用其他的 问号去不掉吗

**Comment by Phunk87** [comment]
是指推流使用了七牛的服务，但是 m3u8 的 ts 切片使用了别的？如何做到？
