### ISSUE TITLE
demo中的"从服务端拿回的 streamJSON"?

### ISSUE THREAD

**Issue by xclidongbo** [pili-engineering/PLCameraStreamingKit#107]
这个streamJSON,我该怎么理解?怎么从服务器端拿到这个?这个格式是固定的吗?
问的比较low.麻烦解答下.
还有这个demo,是不是只有采集视频的功能,没有展示视频的功能吗?
或者说,我从哪里能看到采集到的视频?

**Comment by ruandao** [comment]
他们有个playkit https://github.com/pili-engineering/PLPlayerKit

**Comment by longbai** [comment]
这个json 是调用服务器SDK 生成的，格式固定，参考wiki 文档

**Comment by xclidongbo** [comment]
Thanks,结贴吧...
