### ISSUE TITLE
How to record Live Stream video?

### ISSUE THREAD

**Issue by bintu1234** [pili-engineering/PLCameraStreamingKit#109]
Hi I am working with this library can any tell me how to record a video while Streaming i just check the QNRecord but i don't know how to implement please help me

**Comment by cdkr** [comment]
You may implement `- (CMSampleBufferRef)cameraStreamingSession:(PLCameraStreamingSession *)session cameraSourceDidGetSampleBuffer:(CMSampleBufferRef)sampleBuffer` in `PLCameraStreamingSessionDelegate` to do some extra work with sampleBuffer
