### ISSUE TITLE
希望可以加入重连机制

### ISSUE THREAD

**Issue by kilolumen** [pili-engineering/PLCameraStreamingKit#11]
由wifi切换到4G，或者从连接或断开VPN，都可以重新push

**Comment by Phunk87** [comment]
这里思考后暂且不在 sdk 提供重连，但在 demo 中添加了 reachalibity 类，可以参考来做网络是否连接的判断。

**Comment by ruandao** [comment]
hi 我看到这个是 15年4月30号的， 不知道现在的机制是怎样的， 有没有重连呢？

**Comment by longbai** [comment]
这个建议自己做重试的
