### ISSUE TITLE
可以将依赖“ HappyDNS” 改为建议，而不要写在podspec么？

### ISSUE THREAD

**Issue by ryh** [pili-engineering/PLCameraStreamingKit#119]
可以将依赖 `HappyDNS` 改为建议，而不要写在`podspec`么？

**Comment by longbai** [comment]
为什么？代码里有用到

**Comment by ryh** [comment]
@longbai 先不说安全与否，不是非必需的东西干嘛非得强耦合(?) 的依赖？（还是只example里有 主代码里没有？）
做全家桶的思维做开源真的好么？

**Comment by longbai** [comment]
?? 什么叫全家桶的思维，这个本来就是七牛开源出来的模块，当然我们也可以闭源只用在我们的项目中。你看不到必要性，不等于我们看不到必要性，为什么要用这个，是大量统计的结果。

**Comment by ryh** [comment]
表激动－。－ 开源当然是好的，但不是必须的组件使得一个repo变得很大，比如laravel/framework
 就很多个子模块库，具体如redis 肯定是需求一些redis的库的，但_有的用户_用不到redis 就没有必要写成强依赖，而是用`composer` 的 `suggest`提示用户 (当然iOS和PHP很不同，但可以借鉴一些开源项目的管理方法）
而把所有的必要性全放进去的话...(我们是为你们好，所以...） 这逻辑似曾相识不？

另：劳动节快乐，请节后再回复吧 谢谢

**Comment by longbai** [comment]
就SDK论SDK，SDK如何演变是我们团队内部统计思考讨论权衡的结果。SDK优先考虑的是稳定性，良好处理各种网络情况。 模块加载的灵活性并不是优先考虑的目标，并且这个库是我们多个SDK依赖的一个基础库，所以做了模块分离便于复用。php framework 如果依赖了redis 是丑陋的设计，他并不在用户的依赖路径上，这个场景是不一样的。
