### ISSUE TITLE
建议, demo 里面直接给个可以推流的streamJSON

### ISSUE THREAD

**Issue by ruandao** [pili-engineering/PLCameraStreamingKit#122]
我们服务器有一套验证机制, 每次运行下,我们的机制取得json, 再在demo 里面去黏贴, 很痛苦的

**Comment by longbai** [comment]
这个避免被滥用，尤其是国内，所以您可以自己写个简单的服务器去获取json，demo里直接用http get这个json

**Comment by evaxige** [comment]
麻烦，询问一下，下面的json能够具体解释给一个demo例子么？不太清楚比如hosts里面需要怎么赋值。

// 从服务端拿回的 streamJSON 结构如下：
//    @{@"id": @"stream_id",
//      @"title": @"stream_title",
//      @"hub": @"hub_name",
//      @"publishKey": @"publish_key",
//      @"publishSecurity": @"dynamic", // or static
//      @"disabled": @(NO),
//      @"profiles": @[@"480p", @"720p"],    // or empty Array []
//      @"hosts": @{
//            ...
//      }

**Comment by yuyedaidao** [comment]
这个streamJSON到底是个什么玩意，hosts到底该怎么写
