### ISSUE TITLE
 The 'Pods' target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by peiweichen** [pili-engineering/PLCameraStreamingKit#124]
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'PLCameraStreamingKit', '~> 1.6.2'
```

after run `pod install` :

[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/peiwei/Documents/GitRepos/live/Pods/PLStreamingKit/Pod/Library/lib/libPLStreamingKit.a)

**Comment by lawder** [comment]
Please follow this guide: https://github.com/pili-engineering/PLCameraStreamingKit#Swift

**Comment by peiweichen** [comment]
谢谢你的帮助，但是 readme `配置工程`和`配置到swift`应该放在同一个地方
