### ISSUE TITLE
闪退，没法调用方法

### ISSUE THREAD

**Issue by XuDachuang** [pili-engineering/PLCameraStreamingKit#125]
当我点击开始推流的时候，会出现-[PLStream pushURLWithHost:]: unrecognized selector sent to instance的问题。不能推流。不知道是不是我需要设置什么，还是我的包下载出现问题。希望帮忙解决一下。谢谢

**Comment by cnwangsiyu** [comment]
在项目的 Build Settings 中找到 Other Linker Flags，加入 -ObjC 即可

**Comment by raoxb** [comment]
加了还是会闪退啦
