### ISSUE TITLE
框架

### ISSUE THREAD

**Issue by CoderDuMeng** [pili-engineering/PLCameraStreamingKit#137]
您好， 你这个框架使用 FFMpeg写的 还是用AV 写的 ？

**Comment by cnwangsiyu** [comment]
这个框架并没有使用 FFMpeg 或 AV

**Comment by CoderDuMeng** [comment]
那是？

**Comment by CoderDuMeng** [comment]
那您是，自己写的？用C？

发自 网易邮箱大师
在2016年06月08日 16:33，hzwangsiyu 写道:

这个框架并没有使用 FFMpeg 或 AV
