### ISSUE TITLE
编译警告

### ISSUE THREAD

**Issue by seanxux** [pili-engineering/PLCameraStreamingKit#139]
通过Pod添加的，编译出现如下警告，感觉是静态库build的时候，最低版本没设置
`ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(GPUImageBeautifyFilter.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLAudioCaptureConfiguration.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLVideoCaptureConfiguration.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLCameraFilter.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLWaterMarkCameraFilter.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLBeautyCameraFilter.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLCameraSource.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLGPUImageCameraFilterGroup.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLGPUImageCameraFilter.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLCameraStreamingSession.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/seanxu/Documents/REPOS/Live/bestar_ios/Bestar/Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(PLMicrophoneSource.o)) was built for newer iOS version (9.2) than being linked (8.0)`

**Comment by cnwangsiyu** [comment]
下一个版本我们会修复这个问题的
