### ISSUE TITLE
再咨询一个Audio相关的问题

### ISSUE THREAD

**Issue by qingfeng** [pili-engineering/PLCameraStreamingKit#14]
我把PLCameraStreamingKit和对应的代码引入到自己的工程之后, 出现如下报错:

```
0x1985d7310] >aurioc> 806: failed: -66635 (enable 3, outf< 1 ch,      0 Hz, Float32> inf< 2 ch,  44100 Hz, Int16, inter>)
```

搜索了一下，好像和 `AudioUnitInitialize` 有关? http://stackoverflow.com/questions/28144459/audiounitinitialize-returns-10851-kaudiouniterr-invalidpropertyvalue

求解，感谢～

**Comment by Phunk87** [comment]
感谢反馈，这个问题我这里没能复现，不知道是不是因为设备编码器的区分导致的。可否提供下开发时的设备信息。并且是否是必现呢，如果有可以复现的方法最好，以便我找到具体的原因在哪里。

**Comment by qingfeng** [comment]
我大概知道了，可能是我这边的问题，就是一个视图被加载了两次，就会出现这个问题

2015年5月7日木曜日、0dayZhnotifications@github.comさんは書きました:
