### ISSUE TITLE
ver 1.8.0 i got an error

### ISSUE THREAD

**Issue by danlniel** [pili-engineering/PLCameraStreamingKit#152]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MuseRealTimeProcessor", referenced from:
      objc-class-ref in libPLCameraStreamingKit.a(PLCameraSource.o)

**Comment by betallcoffee** [comment]
1.8.0 暂时不支持模拟器。

**Comment by danlniel** [comment]
谢谢
