### ISSUE TITLE
请问demo真机运行不起来，模拟器可以，是什么原因呢

### ISSUE THREAD

**Issue by qiaovc** [pili-engineering/PLCameraStreamingKit#165]
这是真机编译报的错
![bb9f0bcb-5b1c-4816-9a4d-20c518e7ea20](https://cloud.githubusercontent.com/assets/14816675/18024907/735a12c8-6c49-11e6-8551-a4f3cb993d87.png)

**Comment by cnwangsiyu** [comment]
这个是 Xcode 的缓存问题，Window -> Projects -> delete 可以解决这个问题

**Comment by qiaovc** [comment]
@hzwangsiyu 非常感谢
