### ISSUE TITLE
创建一个推流地址的成本高吗？

### ISSUE THREAD

**Issue by qingfeng** [pili-engineering/PLCameraStreamingKit#18]
因为业务的需求，可能会在用户填写一些信息的时候，就去预先创建一个推流地址出来，但这个推流地址可能未必会被使用到。所以我想知道大量的创建推流地址对七牛这边成本高吗？还是定期删除比较好？

感谢 :beer:

**Comment by why404** [comment]
创建推流地址我们这边没鸭梨的，主要是我们客户的管理成本。

**Comment by qingfeng** [comment]
OK,那我就放心了，感谢回复~
