### ISSUE TITLE
关于延时的问题

### ISSUE THREAD

**Issue by qingfeng** [pili-engineering/PLCameraStreamingKit#22]
今天实测了一下，从RTMP播出去，到HLS获取，中间有47s的延时，就是说HLS收看那一端是47s后的内容，这个延时有什么参数可以控制变小呢？感谢

**Comment by qingfeng** [comment]
已解决 感谢 @googollee

**Comment by bintu1234** [comment]
@qingfeng  I am also facing same issue how you resolve this issue. and how to convert RTMP to HLS
