### ISSUE TITLE
想问下这些流的参数应该怎么填写

### ISSUE THREAD

**Issue by yunisSong** [pili-engineering/PLCameraStreamingKit#24]
PLStream *stream = [PLStream streamWithJSON:@{@"id": @"STREAM_ID",
                                              @"title": @"STREAM_TITLE",
                                              @"hub": @"HUB_NAME",
                                              @"publishKey": @"PUBLISH_KEY",
                                              @"publishSecurity": @"dynamic", // or static
                                              @"disabled": @(NO)}];

我配置了几次都抱错误：ERROR: Problem accessing the DNS. (addr: rtmp)

**Comment by long0419** [comment]
不用配置
yunis notifications@github.com于2015年6月27日 周六14:55写道：

**Comment by Phunk87** [comment]
按照从服务端拿到的 Stream，直接创建 PLStream 就可以，客户端不需要关心字段是什么。
