### ISSUE TITLE
循环出现 missing picture in access unit with size 1877

### ISSUE THREAD

**Issue by kilolumen** [pili-engineering/PLCameraStreamingKit#3]
[h264 @ 0x7fa3eb060c00] missing picture in access unit with size 1877
[h264 @ 0x7fa3ea805600] no frame!
在ffplay播放有时候会循环出现，在app录制不会crash，观看时会crash。重启demo就又变好了

**Comment by Phunk87** [comment]
已添加到 1.1.5 改进中

**Comment by 5kccp** [comment]
同上，missing picture in access unit with size。第一次播放视频的时候会出现，第二次打开就不会，不知道什么问题。会不会是RTMP流本身出了问题？
