### ISSUE TITLE
streamJSON，rtmpPublishHost的一些疑问

### ISSUE THREAD

**Issue by anotheren** [pili-engineering/PLCameraStreamingKit#32]
我大概是想做一个RTMP的推流客户端，看之前有人提过streamJSON结构中的有些参数不太清楚，反馈是“具体参数由 pili 后台返回”，我理解为是你们提供的某种RTMP视频流的服务吧，具体着了一下也找不到相关的资料。
但我现在的需求是把视频流推送到某一个指定地址，那我也没有从pili的后台拿streamJSON。如果我自己直接定义一个streamJSON，其中的id，title，hub，publishKey，publishSecurity，disabled分别又怎么定义呢？包括rtmpPublishHost又该填什么？我看了很久也没明白，我就随便填了，测试了各种组合，发现session生成后，其pushURL还是nil，怪不得后面使用startWithCompleted方法就一直60秒超时呢。
不过似乎startWithPushURL这个方法还可用，可以将将视屏流推送到指定的URL，但是感觉也是挺混乱的。希望能补全这方面的说明，谢谢。

**Comment by Phunk87** [comment]
PLCameraStreamingKit 需要配合 Pili 流媒体服务一起使用的，如果你们有做直播的需求，可以讲可公开的联系方式，如邮箱留一下，我们可以了解下需求，确认一下 pili 是否满足你们的业务需求。

**Comment by brunolens** [comment]
Hello

Could you explain about streamJSON's every fields?
I'm not sure what the "hub", "publishkey", "publishSecurity" information on this JSON Dictionary mean.

Thanks.

**Comment by thereqwe** [comment]
你好 我们公司想做一个视频直播的app 你的代码很符合,我的邮箱是thereqwe@qq.com 想用一下你们的流媒体服务.
