### ISSUE TITLE
startWithCompleted失败的代理回调问题

### ISSUE THREAD

**Issue by 5kccp** [pili-engineering/PLCameraStreamingKit#34]
startWithCompleted失败后会回调- (void)cameraStreamingSession:(PLCameraStreamingSession *)session streamStateDidChange:(PLStreamState)state进入PLStreamStateDisconnected状态，但我觉得这样不合理。PLStreamStateDisconnected只应该发生在PLStreamStateConnected之后，只有连上后才会有断开的的状态，但startWithCompleted失败的过程中并没有经历PLStreamStateConnected状态。

**Comment by Phunk87** [comment]
感谢反馈，这部分我会考虑做更改。
