### ISSUE TITLE
fps不能有20吗，只有15和30

### ISSUE THREAD

**Issue by 5kccp** [pili-engineering/PLCameraStreamingKit#37]
我想在20fps上提高码率，提高分辨率，想在512kbps上面获取更清晰的画面。但现在是有15fps和30fps。30fps的情况下，码率提高了很多，但画面还是模糊。如果我提高分辨率，保持码率不变的话，画面会出现方块。

**Comment by Phunk87** [comment]
暂且不会考虑添加额外的视频质量选项，低于 30 后面临的问题不是 15 或者 20 或者 25, 而是视频质量一定会有损失。
