### ISSUE TITLE
可不可以增加images推流

### ISSUE THREAD

**Issue by 5kccp** [pili-engineering/PLCameraStreamingKit#38]
我看到VideoCore0.3.1增加了“Introduction of pixel buffer sources so you can add images to broadcast.”。现在有一个需求就是，需要读取图像并加入音轨来推流。

**Comment by Phunk87** [comment]
该需求在重构版本中有，之后会添加

**Comment by Phunk87** [comment]
请尝试 https://github.com/pili-engineering/PLStreamingKit
