### ISSUE TITLE
PLCameraStreamingKit 可以推送直播到red5/Wowza等这些流媒体服务器吗？

### ISSUE THREAD

**Issue by ruxuejia** [pili-engineering/PLCameraStreamingKit#39]

**Comment by jonesking** [comment]
沒辦法喔 要用七牛的雲存儲

**Comment by ruxuejia** [comment]
@jonesking 七牛云存储？那这个项目需要搭配什么服务器来使用呢？

**Comment by jonesking** [comment]
你可以參考一下 他們的文檔
https://www.evernote.com/l/AdR8KGdoE_lHLLzBPz9DNgS1JfDF84K_jX8

這我整理的, 如果你的用戶在國內, 沒必要使用wowza

wowza的好處在於他跟jwplayer AWS 國外CDN良好的整體解決方案

這些在中國境內不是必需品

**Comment by ruxuejia** [comment]
@jonesking  谢谢你的资料 我再详细看看

**Comment by cnsuer** [comment]
@jonesking 能不能提供一个demo啊，刚接触这个，你分享的这个文档又不能看了，它这个怎么推流地址怎么填？？
