### ISSUE TITLE
能不能根据屏幕自动取宽高比，录制什么播放的就是什么

### ISSUE THREAD

**Issue by kilolumen** [pili-engineering/PLCameraStreamingKit#4]
push时是全屏录制的，播放时会裁剪很多，比如设置的4：3 (640:480),播放时会根据录制时屏幕的宽度为播放时的长边进行裁剪，就是把手机屏幕的上边，和下边很多都裁剪了

**Comment by Phunk87** [comment]
Fixed on 1.1.2
