### ISSUE TITLE
How to import to Swift project?

### ISSUE THREAD

**Issue by ppamorim** [pili-engineering/PLCameraStreamingKit#42]
I`m trying to import this library to a swift project, but I can`t. This don`t compile. :(

**Comment by Phunk87** [comment]
1. Make sure you add `use_frameworks` in your Podfile
2. Add bridging header which include code `#import <PLCameraStreamingKit/PLCameraStreamingKit.h>`
3. Add bridging header path in Build Settings.
4. Good luck.

**Comment by ppamorim** [comment]
![captura de tela 2015-10-14 as 09 04 58](https://cloud.githubusercontent.com/assets/5521682/10482975/cfa8a3d8-7252-11e5-813c-5e3b68d8ef2a.png)
![captura de tela 2015-10-14 as 09 04 48](https://cloud.githubusercontent.com/assets/5521682/10482976/cfa8e0e6-7252-11e5-9fb9-951139c6951c.png)

Not working yet, the library has not shown at "Linked Frameworks and Libraries". :(
Kingpin works fine here...

**Comment by Phunk87** [comment]
Just `import Pods` in your swift file. You should be able to use PLCameraStreamingKit class.
