### ISSUE TITLE
PLStream Dictionary for Wowza Server 

### ISSUE THREAD

**Issue by chinnasamymca** [pili-engineering/PLCameraStreamingKit#43]
NSDictionary *streamJSON  =     @{@"id": @"live",
          @"title": @"Sample",
          @"hub": @"live",
          @"publishKey": @"publish_key",
          @"publishSecurity": @"dynamic", // or static
          @"disabled": @(NO),
          @"profiles": @[@"480p", @"720p"],    // or empty Array []
          @"hosts": @{
                  @"publish": @{
                        @"rtmp": @"xx.xx.xx.xx:1935"
                    }
          }

```
                                  }; 
```

Is it right configurations for Wowza server. 

Thanks, 
Chinna

**Comment by shubhank008** [comment]
@chinnasamymca did that work out for you ?

**Comment by chinnasamymca** [comment]
No, I have not tested. How about you ?

**Comment by Phunk87** [comment]
streaming to pili server only.
