### ISSUE TITLE
最新的PLCameraStreamingKit和PLPlayerKit同时在一个项目中使用，有冲突库

### ISSUE THREAD

**Issue by wdzlwd** [pili-engineering/PLCameraStreamingKit#47]
可以给与修正吗

**Comment by Phunk87** [comment]
已知在模拟器运行会有冲突提示，真机不会有。

**Comment by wdzlwd** [comment]
冲突库依然存在
Installing PLCameraStreamingKit 1.4.13 (was 1.4.11)
Installing PLPlayerKit 2.0.1 (was 2.0.0)
......
......
......
duplicate symbol _RTMP_LogHexString in:
    /Users/.../Pods/PLCameraStreamingKit/Pod/Library/lib/libPLCameraStreamingKit.a(log.o)
    /Users/.../Pods/PLPlayerKit/Pod/Library/lib/libPLPlayerKit.a(log.o)
ld: 58 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Phunk87** [comment]
duplicate #62
