### ISSUE TITLE
添加自行绘制 CMSampleBufferRef 的支持的疑问

### ISSUE THREAD

**Issue by bellchen** [pili-engineering/PLCameraStreamingKit#49]
这个功能是指摄像头和麦克风的采集不在sdk中提供，而是我来提供，而SDK只是把CMSampleBufferRef编码然后推流到rtmp服务器吗？
如果是这样就太好了

**Comment by bellchen** [comment]
1.4.5没见到api diff呀，怎么使用这个功能呀？

**Comment by Phunk87** [comment]
你可以尝试使用 https://github.com/pili-engineering/PLStreamingKit 来做，PLStreamingKit 中的数据源由开发者提供，SDK 只负责编码和推流。
