### ISSUE TITLE
muted变更的问题

### ISSUE THREAD

**Issue by 5kccp** [pili-engineering/PLCameraStreamingKit#52]
muted默认是NO，当muted为YES的时候，视频消音的，这是对的，但是当muted再次设置为NO的时候，视频是继续没有声音的，这是否为bug

**Comment by Phunk87** [comment]
mute 的处理策略有过变更，你说的现象我未能重现，请问你是什么机型及系统型号，观看时是看的 rtmp 还是 hls?

**Comment by 5kccp** [comment]
后来测正常了
