### ISSUE TITLE
publish无法使用域名地址

### ISSUE THREAD

**Issue by wdzlwd** [pili-engineering/PLCameraStreamingKit#53]
使用域名地址时无法连接和推流
log如下：
CameraSource: startRunning
MicrophoneSource: startRunning
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
Stream State: Connecting
Stream State: Error. Error Domain=pili.rtmp Code=-1014 "RTMP connect stream failed." UserInfo={NSLocalizedDescription=RTMP connect stream failed.}

**Comment by Phunk87** [comment]
是使用的自己的 rtmp 服务器还是 pili 的？

**Comment by iBlackDev** [comment]
我是用自己搭建的rtmp服务器，也是这个问题。另外想问下，PLCameraStreamingKit和PLPlayerKit支持自己搭建的服务吗？@0dayZh

**Comment by weirdyu** [comment]
测试了下，支持自己的rtmp服务器，域名地址还没有测试。

**Comment by mirosun** [comment]
@weirdyu 如何使用自己的rtmp服务器？

**Comment by weirdyu** [comment]
@MiroPro 配置streamJson
NSDictionary *streamJson = @{@"publishSecurity": @"static",
                                         @"hub": @"",
                                         @"title": @"",
                                         @"publishKey": @"",
                                         @"disabled":@(NO),
                                         @"hosts":
                                             @{@"live":@{@"http": @"",
                                                         @"hdl": @"",
                                                         @"hls": @"",
                                                         @"rtmp": @""},
                                               @"playback":@{@"http": @"",
                                                             @"hls": @""},
                                               @"publish": @{@"rtmp": @""}
                                               },
                                         @"updatedAt": @"",
                                         @"id": @"",
                                         @"createdAt": @""};
            PLStream *stream = [PLStream streamWithJSON:streamJson];

rtmp://{rtmp_publish_host}/{hub}/{stream_title}?key={publishKey}

**Comment by mirosun** [comment]
@weirdyu 非常感谢，试了一下不知为何不行，我这里有个rtmp://example.com/lcw/ 还有一个串码流。第一次弄直播。还望指教

**Comment by weirdyu** [comment]
@MiroPro  https://github.com/qiniudemo/qiniu-live-iOS
在QNPiliCameraVC.m中配置streamJson试试

**Comment by mirosun** [comment]
@weirdyu非常感谢

**Comment by Phunk87** [comment]
当前并不支持第三方的服务器，另外 stream 结构在未来重构中可能会做变更或移出， @weirdyu @MiroPro
