### ISSUE TITLE
[PLSendingBuffer clean]的时候会偶发EXC_BAD_ACCESS / KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by 5kccp** [pili-engineering/PLCameraStreamingKit#58]
EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
0   libobjc.A.dylib
1   CoreFoundation
2   AGVideoDev  -[PLSendingBuffer clean]    [PLSendingBuffer.m line 427]
3   AGVideoDev  -[PLCameraStreamingSession rtmpSession:didDisconnectWithError:] [PLCameraStreamingSession.m line 438]
4   AGVideoDev  StreamStateCallback [PLRTMPSession.m line 40]
5   AGVideoDev  rtmp_error_callback [push.c line 38]
6   AGVideoDev  RTMP_Close  [rtmp.c line 3610]
7   AGVideoDev  WriteN  [rtmp.c line 1536]
8   AGVideoDev  RTMP_SendPacket [rtmp.c line 3517]
9   AGVideoDev  pili_write_flv_tag  [push.c line 179]
10  AGVideoDev  -[PLRTMPSession sendPacket] [PLRTMPSession.m line 277]
11  libdispatch.dylib
12  libdispatch.dylib
13  libdispatch.dylib
14  libdispatch.dylib
15  libdispatch.dylib
16  libdispatch.dylib
17  libsystem_pthread.dylib
18  libsystem_pthread.dylib

**Comment by cnwangsiyu** [comment]
已解决
