### ISSUE TITLE
解决 PLPlayer 与 PLCameraStreamingKit 底层依赖重复引用的问题

### ISSUE THREAD

**Issue by Phunk87** [pili-engineering/PLCameraStreamingKit#62]

**Comment by CheneyZJ** [comment]
是不是duplicate symbol _RTMP_SetOpt 和 _RTMP_DefaultFlashVer,今天刚集成的就有这错误,是一个问题吗

**Comment by wdzlwd** [comment]
同时使用会出现log.o amf.o error.o rtmp.o冲突，把它们手动从其中一个.a去掉后，出现rtmp部分方法找不到；可否将它们放在公用.a里面，这样添加2个引用一个就可以了

**Comment by Phunk87** [comment]
@CheneyZJ @wdzlwd 是底层 librtmp 库依赖问题，会抽离出一个公有 Pods 作为依赖解决这个问题。暂且这个问题不影响真机调试，对模拟器运行会有影响。

**Comment by wdzlwd** [comment]
👍期待最新版本

**Comment by cnwangsiyu** [comment]
已解决
