### ISSUE TITLE
请问是只有在wifi环境下才能推流成功吗

### ISSUE THREAD

**Issue by hahaGitHub** [pili-engineering/PLCameraStreamingKit#68]
iOS直播推流 开始我在wifi环境下推流 当我关闭wifi 切换到自己的蜂窝数据下时 推流就不成功了
请问是只有在wifi环境下才能推流成功吗

**Comment by Phunk87** [comment]
最新版本是否还有这个问题？

**Comment by winterfeel** [comment]
是因为加上了DNS解析的缘故好像，我们删掉了DNS解析就可以了。

方法仅供参考：
修改Pods项目下Pods/HappyDNS/QNDnspodFree.h和QNDnspodEnterprise.h
把里面的query方法改成：

NSString *ips = domain.domain;//[ip1 objectAtIndex:0];
NSMutableArray *ret = [[NSMutableArray alloc] initWithCapacity:1];
QNRecord *record = [[QNRecord alloc]init:ips ttl:3600 type:kQNTypeA];
[ret addObject:record];
return ret;

就是不让他再进行DNS查询了，因为我们的推流地址直接是ip，这里它查询到空所以出错了。
这样修改后直接返回ip，我们在蜂窝数据下推流成功了。

不保证一定有效，仅供参考。
