### ISSUE TITLE
[AVAssetWriter startSessionAtSourceTime:] Cannot call method when status is 0'

### ISSUE THREAD

**Issue by kilolumen** [pili-engineering/PLCameraStreamingKit#7]
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '**\* -[AVAssetWriter startSessionAtSourceTime:] Cannot call method when status is 0'
**\* First throw call stack:
(0x1848482d8 0x19606c0e4 0x18304caf8 0x183046f90 0x100299b8c 0x1830488bc 0x18304842c 0x1830e0cd0 0x1847ee2c4 0x18472b450 0x18474f570 0x185041a0c 0x186e9b2a4 0x186ea324c 0x101bcab50 0x101bc4f94 0x101bdc848 0x101bc71c0 0x101bd0384 0x101bc82c4 0x101bd25d4 0x101bd4248 0x19689d22c 0x19689cef0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Phunk87** [comment]
增加 iOS 8 编码优化后，在 iOS 8 及以上的系统这个问题会避免。

**Comment by Phunk87** [comment]
1.2.14 后 iOS 8 不会再有此问题。
