### ISSUE TITLE
偶尔会出现推流没有声音的问题

### ISSUE THREAD

**Issue by 5kccp** [pili-engineering/PLCameraStreamingKit#71]

**Comment by 5kccp** [comment]
暂时不知道是否出现在某些设备，但iPhone6出现了，录音权限是获取了的，因为用一个设备，大部分视频是有声音的，偶尔会出现一个全程无声音的。

**Comment by ruandao** [comment]
我也会出现同样的问题， 在第一次推流时， 视频推流正常，但是音频推流不正常， 退出去后，重建，则音频推流恢复正常 不知道是不是因为音频的开启是在startWithCompleted 方法中的缘故

**Comment by longbai** [comment]
可能是推流音频被占用，可能是被你的应用或者其他应用占了。

**Comment by ruandao** [comment]
恩, 后来我的问题解决了, 我这边出现的问题是 audio session 的 category 被设为 仅允许听,不允许录

**Comment by cnwangsiyu** [comment]
已解决
