### ISSUE TITLE
升级至1.5.0  无接口requestCaptureImageWithComplete

### ISSUE THREAD

**Issue by hahaGitHub** [pili-engineering/PLCameraStreamingKit#75]
升级至1.5.0后，发现截取视频image的接口requestCaptureImageWithComplete没有了？
是确定以后都没有了吗？

**Comment by cnsuer** [comment]
@hahaGitHub 你好，刚刚接触这个sdk，请问怎么设置推流地址啊？？？？？

**Comment by gukemanbu** [comment]
同问~~

**Comment by Phunk87** [comment]
@hahaGitHub 1.5.0 去除了，开放了采集源代码，如果你需要有对数据采集做额外的动作，都可以自己来做。

**Comment by Phunk87** [comment]
@cnsuer 需要开通 pili 直播服务。
