### ISSUE TITLE
60 fps

### ISSUE THREAD

**Issue by BohdanBilonoh** [pili-engineering/PLCameraStreamingKit#76]
Hi!
Tried to create PLCameraStreamingSession on iPhone 6s+ with following configuration

``` swift
let size = CGSize(width: 720, height: 1280)
let frameRate: UInt = 60
let keyframeInterval: UInt = 1
let bitrate: UInt = 3000000
let videoConfiduration = PLVideoStreamingConfiguration(userDefineDimension: size, videoFrameRate: frameRate, videoMaxKeyframeInterval: keyframeInterval, videoBitrate: bitrate)
let audioConfiduration = PLAudioStreamingConfiguration.defaultConfiguration()

self.session = PLCameraStreamingSession(videoConfiguration: videoConfiduration, audioConfiguration: audioConfiduration, stream: stream, videoOrientation: .Portrait)
```

Crashed in PLCameraSource line 83: device.activeVideoMinFrameDuration = CMTimeMake(1, self.videoConfiguration.videoFrameRate)

Stack trace:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'range out of support'
**\* First throw call stack:
(0x182d2d900 0x18239bf80 0x1000982b0 0x100098618 0x10007c804 0x10007bc7c 0x10007b850 0x10007b57c 0x10124dbf0 0x10124dbb0 0x10125a6c8 0x1012518a0 0x10124dbb0 0x10125ce10 0x10125c4d8 0x182995470 0x182995020)
libc++abi.dylib: terminating with uncaught exception of type NSException

Thanks!

**Comment by Phunk87** [comment]
We lock 30 fps as max video fps for live streaming in SDK.
