### ISSUE TITLE
在应用运行过程中，变更应用的授权设置会崩溃

### ISSUE THREAD

**Issue by shingwasix** [pili-engineering/PLCameraStreamingKit#79]
如题，包括图片、摄像头和麦克风的授权设置。
在iOS8和iOS9下均会导致应用崩溃闪退，即使应用没有调用过任何检查授权状态的API，崩溃问题依然存在。

**Comment by Phunk87** [comment]
是指变更后，进入 App 就崩溃，还是变更后 App 被杀掉了，重新启动？

**Comment by shingwasix** [comment]
变更后 App 被杀掉。后来经我调查发现所有其他应用都存在这个问题，而且我尝试过使用过其他第三方摄影库也一样存在这个问题。确定这是iOS系统的一个bug（也有可能是iOS本来就打算这么设计的），与七牛推流库无关。
