### ISSUE TITLE
画面和声音会出现不同步

### ISSUE THREAD

**Issue by 5kccp** [pili-engineering/PLCameraStreamingKit#80]
偶发一个问题，就是声音和画面不同步，用的是1.4.13的SDK。回放视频如下http://playback-hls.youcan.mobi/appgame/568b2ac8fb16df262e00048a.m3u8?start=1451961033&end=1451962217

**Comment by Phunk87** [comment]
看了下应该是推流端网络不佳出现了视频丢帧，并无音画不同步。
