### ISSUE TITLE
how to connect to red 5 server using this library is it support to red 5 or wowza?

### ISSUE THREAD

**Issue by bintu1234** [pili-engineering/PLCameraStreamingKit#83]
I am using this library but the streamingSession is not starting is it support the red 5 server

**Comment by Phunk87** [comment]
Currently, we just provide PLCameraStreamingKit as a part of Pili Live Streaming Service which is still in beta. We'd like to support more live streaming service someday.

**Comment by bintu1234** [comment]
@0dayZh  Thanks for the replay but some guys saying that it is working with red 5 server is't it?
