### ISSUE TITLE
PLStream对应的参数没有注释，对应的rtmp信息该如何配置？

### ISSUE THREAD

**Issue by MrJackL** [pili-engineering/PLCameraStreamingKit#85]
如题；Demo中没有PLStream的参数注释，请给出配置rtmp的示例。

**Comment by MrJackL** [comment]
另外，请问域名rtmp链接可以推流么？例如：rtmp://example.com/live/2342892834

**Comment by Phunk87** [comment]
SDK 需要配合霹雳云直播服务一同使用，谢谢。
