### ISSUE TITLE
求教，我的推流地址是rtmp://xxx.com/live/room/chat 应该怎么设置streamJSON

### ISSUE THREAD

**Issue by wheelswang** [pili-engineering/PLCameraStreamingKit#87]
发布点是/live/room
流名是chat

我是这样配置的：
@"id": @"chat",
@"title": @"chat",
@"hub": @"/live/room",
但是抓包发现推流时
connect /live
fcpublish room/chat

期望的是
connect /live/room
fcpublish chat

**Comment by weirdyu** [comment]
供参考：http://devtools.qiniu.com/pili-guide-v1.pdf
rtmp://{rtmp_publish_host}/{hub_name}/{stream_title}?key={publishKey}

**Comment by wheelswang** [comment]
hub_name里有/这样的字符可以支持一下吗，之前的版本是可以的

**Comment by wheelswang** [comment]
目前的版本把hub_name中第二个/后的字符当成流名来处理了

**Comment by Phunk87** [comment]
当前 SDK 暂不为霹雳直播之外的服务提供支持，感谢关注 @weirdyu @wheelswang
