### ISSUE TITLE
使用域名推流会有问题，连接时tcUrl属性不正确

### ISSUE THREAD

**Issue by wheelswang** [pili-engineering/PLCameraStreamingKit#88]
RTMP发起connect连接的时候
tcUrl属性使用了ip，应该使用域名才对

**Comment by wheelswang** [comment]
![47a65a74-b997-49bc-892e-54931bf23f2a](https://cloud.githubusercontent.com/assets/6286327/12613515/3932801e-c535-11e5-9d65-fe65d9946125.png)

**Comment by Phunk87** [comment]
内置了 dns 解析。
