### ISSUE TITLE
How to set hosts in PLStream.

### ISSUE THREAD

**Issue by DaGeTian** [pili-engineering/PLCameraStreamingKit#90]
Hello, Sir.
Wonderful!
But then I have one problem.
In PLSStream, hosts is a NSDictionary.
How to set hosts static? I means, I don't know how to set key. 
And then how can I test your example app? What can I use Stream Server?

**Comment by 0dayZh** [comment]
Nowadays, this lib is bind to Qiniu Pili Streaming Service, you cannot set PLStream info by yourself.
