### ISSUE TITLE
Problems with lib libPLStreamingKit.a

### ISSUE THREAD

**Issue by alexandrogomes** [pili-engineering/PLCameraStreamingKit#91]
hello, firstly thanks for you code it's great. I'm testing in my application install and i had problems with the lastest version. The 'Pods-testLib' target has transitive dependencies that include static binaries: ...Pods/PLStreamingKit/Pod/Library/lib/libPLStreamingKit.a

Please, i need you help

Regards,
  Alex

**Comment by Phunk87** [comment]
Thanks for your issue. If you run `pod update` successfully, the dependencies should be installed. However, you may not use the PLCameraStreamingKit even you have install it successfully, for this lib is bind to Qiniu Pili Streaming Service.
