### ISSUE TITLE
蜂窝数据下时 推流就不成功， 请问怎么配置网络环境

### ISSUE THREAD

**Issue by makeyu** [pili-engineering/PLCameraStreamingKit#94]

**Comment by longbai** [comment]
wifi 情况 是 好的？ 麻烦给下 stream 配置，还有网络信息

**Comment by makeyu** [comment]
您好这是我的配置 ，您看是怎么回事，网络是 4G 移动（联通可以
）
NSDictionary *streamJSON =  @{@"id": @"stream_id",
                                      @"title": title,
                                      @"hub": @"live",
                                      @"publishKey": @"123456",
                                      @"publishSecurity": @"static", // or static//dynamic
                                      @"disabled": @(YES),
                                      @"profiles": @[],    // or empty Array []
                                      @"hosts": @{
                                              @"publish": @{

```
                                                  @"rtmp":@"32_1023live   
```

223.202.15.183:1935"
                                                      },
                                              @"play": @{
                                                      @"rtmp":@"32_1023live  
223.202.15.183:1935"
                                                      @"hls": @"0"
                                                      }
                                              },
                                      };

**Comment by makeyu** [comment]
Wi-Fi 下没有任何问题，主要是 4G 网

**Comment by winterfeel** [comment]
是因为加上了DNS解析的缘故好像，我们删掉了DNS解析就可以了。

方法仅供参考：
修改Pods项目下Pods/HappyDNS/QNDnspodFree.h和QNDnspodEnterprise.h
把里面的query方法改成：

NSString *ips = domain.domain;//[ip1 objectAtIndex:0];
NSMutableArray *ret = [[NSMutableArray alloc] initWithCapacity:1];
QNRecord *record = [[QNRecord alloc]init:ips ttl:3600 type:kQNTypeA];
[ret addObject:record];
return ret;

就是不让他再进行DNS查询了，因为我们的推流地址直接是ip，这里它查询到空所以出错了。
这样修改后直接返回ip，我们在蜂窝数据下推流成功了。

不保证一定有效，仅供参考。

**Comment by makeyu** [comment]
好的 谢谢

**Comment by makeyu** [comment]
合作 包括 app端 和后台切片等，
