### ISSUE TITLE
推流错误 

### ISSUE THREAD

**Issue by dapiaowudi** [pili-engineering/PLCameraStreamingKit#97]
PLStream配置如下  
NSDictionary *streamJSON = @{@"id": @"",
                                 @"title": @"",
                                 @"hub": @"",
                                 @"publishKey": @"",
                                 @"publishSecurity": @"static", // or static
                                 @"disabled": @(NO),
                                 @"profiles": @[],    // or empty Array []
                                 @"hosts": @{
                                         @"publish": @{
                                                 @"rtmp": @"live-send.acg.tv/live_2763567_7823365?streamname=live_2763567_7823365&key=3293d27605fdce44466711fee73b6700"
                                                 },
                                         @"play": @{
                                                 @"rtmp": @"live-send.acg.tv/live_2763567_7823365?streamname=live_2763567_7823365&key=3293d27605fdce44466711fee73b6700"
                                                 }
                                         }
                                 };
请问是我配置错了么  还是因为什么

**Comment by dapiaowudi** [comment]
`    NSDictionary *streamJSON = @{@"id": @"",
                                 @"title": @"",
                                 @"hub": @"",
                                 @"publishKey": @"",
                                 @"publishSecurity": @"static", // or static
                                 @"disabled": @(NO),
                                 @"profiles": @[],    // or empty Array []
                                 @"hosts": @{
                                         @"publish": @{
                                                 @"rtmp": @"live-send.acg.tv/live_2763567_7823365?streamname=live_2763567_7823365&key=3293d27605fdce44466711fee73b6700"
                                                 },
                                         @"play": @{
                                                 @"rtmp": @"live-send.acg.tv/live_2763567_7823365?streamname=live_2763567_7823365&key=3293d27605fdce44466711fee73b6700"
                                                 }
                                         }
                                 };`

**Comment by Phunk87** [comment]
当前版本暂且不支持推流到自己的服务器，谢谢关注。
