### ISSUE TITLE
CocoaPods 依赖的问题

### ISSUE THREAD

**Issue by sipdar** [pili-engineering/PLCameraStreamingKit#99]
swift 项目中 cocoapods 的pod file 中 不管用  use_frameworks! 还是不用 貌似都有兼容问题 能否把静态库换成framework？

<img width="1309" alt="2016-02-26 11 59 22" src="https://cloud.githubusercontent.com/assets/1386469/13342824/77021a5a-dc80-11e5-908e-574d359611b1.png">

**Comment by longbai** [comment]
我们看下

**Comment by JackDPro** [comment]
+1 ,swift 不支持

**Comment by Phunk87** [comment]
我做了简单的查询，确认问题在于 Pods 配置工程时，如果同时引用 static framework 和 dynamic framework 时会出错，相应找到两个可以进一步研究的文档，希望可以有些帮助。 @dongkaipo @sipdar 

https://github.com/googleads/googleads-mobile-ios-examples/issues/12
https://github.com/CocoaPods/CocoaPods/issues/2926
